# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0017_tickettimetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMoneyTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(help_text='Money spent on ticket', verbose_name='Money Spent')),
                ('tracked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/Time tracked', verbose_name='Tracked At')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_track', to='helpdesk.Ticket', verbose_name='Ticket')),
                ('tracked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_track', to=settings.AUTH_USER_MODEL, verbose_name='Tracked By')),
            ],
            options={
                'permissions': (('change_others_ticketmoneytrack', 'Can change ticket money track of others'), ('delete_others_ticketmoneytrack', 'Can delete ticket money track of others')),
            },
        ),
    ]
