# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_ticketmoneytrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('text', models.TextField(help_text='The context available to you includes {{ ticket }}, {{ queue }}, and depending on the time of the call: {{ resolution }} or {{ comment }}.', verbose_name='Plain Text')),
                ('locale', models.CharField(blank=True, help_text='Locale of this template.', max_length=10, null=True, verbose_name='Locale')),
            ],
            options={
                'verbose_name_plural': 'sms templates',
                'verbose_name': 'sms template',
                'ordering': ('template_name', 'locale'),
            },
        ),
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='sms', max_length=16, verbose_name='Notify Type')),
                ('to', models.CharField(help_text='Enter a full e-mail address, or sms number', max_length=150, verbose_name='E-Mail Address or SMS Number')),
                ('priorities', models.CharField(blank=True, help_text='Leave blank to be ignored on all priorities, or select those priorities wish to be notified.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:\\d+\\,)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('statuses', models.CharField(blank=True, help_text='Leave blank to be ignored on all statuses, or select those statuses wish to be notified.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:\\d+\\,)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('queues', models.ManyToManyField(blank=True, help_text='Leave blank to be ignored on all queues, or select those queues you wish to be notified.', to='helpdesk.Queue')),
            ],
            options={
                'verbose_name_plural': 'Ticket notification',
                'verbose_name': 'Ticket notification',
            },
        ),
    ]
