# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_initial_ticket_notification_sms_templates_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnotification',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Display Name'),
        ),
    ]
