# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_auto_20170819_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.DateTimeField(blank=True, help_text='Repair completed at', null=True, verbose_name='Completed'),
        ),
    ]
