# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-14 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0024_ticket_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='completed',
        ),
    ]
