# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0025_remove_ticket_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due on'),
        ),
    ]
