# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 06:32
from __future__ import unicode_literals

import os
import shutil

from django.conf import settings
from django.db import migrations, models
import helpdesk.models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Attachment = apps.get_model("helpdesk", "Attachment")
    for attachment in Attachment.objects.using(db_alias).all():
        filename = os.path.split(attachment.file.name)[-1]
        new_filename = helpdesk.models.attachment_file_path_func(attachment, filename)
        new_filepath = os.path.join(settings.MEDIA_ROOT, new_filename)
        new_dirpath = os.path.split(new_filepath)[0]
        old_filepath = os.path.join(settings.MEDIA_ROOT, attachment.file.name)

        os.makedirs(new_dirpath, 0o777, exist_ok=True)
        if os.path.exists(old_filepath):
            shutil.copy(old_filepath, new_filepath)
        attachment.file.name = new_filename
        attachment.save()


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Attachment = apps.get_model("helpdesk", "Attachment")
    for attachment in Attachment.objects.using(db_alias).all():
        filename = os.path.split(attachment.file.name)[-1].split('-')[-1]
        ticket = attachment.followup.ticket
        ticket_for_url = u"%s-%s" % (ticket.queue.slug, ticket.id)
        new_filename = 'helpdesk/attachments/%s/%s/%s' % (ticket_for_url, attachment.followup.id, filename)
        new_filepath = os.path.join(settings.MEDIA_ROOT, new_filename)
        new_dirpath = os.path.split(new_filepath)[0]
        old_filepath = os.path.join(settings.MEDIA_ROOT, attachment.file.name)

        os.makedirs(new_dirpath, 0o777, exist_ok=True)
        if os.path.exists(old_filepath):
            shutil.copy(old_filepath, new_filepath)
        attachment.file.name = new_filename
        attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0026_auto_20171108_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=1000, upload_to=helpdesk.models.attachment_file_path_func, verbose_name='File'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
