# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_auto_20180829_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('title',), 'permissions': (('queue_super_access', 'Has super access to Queue'),), 'verbose_name': 'Queue', 'verbose_name_plural': 'Queues'},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'permissions': (('saved_search_super_access', 'Has super access to SavedSearch'),), 'verbose_name': 'Saved search', 'verbose_name_plural': 'Saved searches'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': 'created', 'ordering': ('id',), 'permissions': (('ticket_super_access', 'Has super access to Ticket'),), 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
